### ISSUE TITLE
List don't show description

### ISSUE THREAD

**Issue by Matteo-Catalano** [develhope/team-1-choose-your-own-beer#26]
- [ ] **List in home don't show right cardview style** (font,description,size)

**Comment by vincenzocostagliola** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [List don't show description](https://trello.com/c/54B4w8zu/25-list-dont-show-description)

**Comment by vincenzocostagliola** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [List don't show description](https://trello.com/c/54B4w8zu/25-list-dont-show-description)
