### ISSUE TITLE
Gear icon instead of "SETTINGS" text in profile fragment

### ISSUE THREAD

**Issue by alessiodicorato** [develhope/team-1-choose-your-own-beer#54]

**Comment by alessiodicorato** [comment]
![profile settings](https://user-images.githubusercontent.com/85505676/167381490-198dbc1e-4b01-434e-bace-7c2f30b6e7a6.png)

**Comment by vincenzocostagliola** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gear icon instead of "SETTINGS" text in profile fragment](https://trello.com/c/XzdEx5Iz/23-gear-icon-instead-of-settings-text-in-profile-fragment)
