### ISSUE TITLE
"Go to detail" button text not perfectly centered

### ISSUE THREAD

**Issue by alessiodicorato** [develhope/team-1-choose-your-own-beer#55]
![buttontxt](https://user-images.githubusercontent.com/85505676/167381924-d60db4c9-eb05-4528-b8e2-5dd9db26f3ed.png)

**Comment by vincenzocostagliola** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Go to detail" button text not perfectly centered](https://trello.com/c/Yvggx7PV/22-go-to-detail-button-text-not-perfectly-centered)
