### ISSUE TITLE
Remove '=' sign from app version text

### ISSUE THREAD

**Issue by alessiodicorato** [develhope/team-1-choose-your-own-beer#56]
![appvrs](https://user-images.githubusercontent.com/85505676/167382173-99cf3a75-73b1-4525-9d56-a36150073df9.png)

**Comment by vincenzocostagliola** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove '=' sign from app version text](https://trello.com/c/uKis4S0H/21-remove-sign-from-app-version-text)
